### ISSUE TITLE
Composer version

### ISSUE THREAD

**Issue by igorsKolcinsMagebit** [clawrock/magento2-debug#15]
In the readme file it is written that the extension supports PHP 8.1, but when running the composer require, facing an error:
`clawrock/magento2-debug 1.0.0 requires php ~5.6.0|~7.0.0|~7.1.0 -> your php version (8.1.19) does not satisfy that requirement`

**Comment by makao** [comment]
Try latest version, 1.0.0 doesn't support PHP 8.1.
