### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by dronerdk** [clawrock/magento2-debug#19]
Hello
We try to uninstall but we get this error:
There is an error in /var/www/droner.dev/public_html/vendor/magento/framework/Code/Reader/ClassReader.php at line: 34
Class "ClawRock\Debug\Plugin\Collector\CacheCollectorPlugin" does not exist#0

**Comment by dronerdk** [comment]
There is an error in /var/www/droner.dev/public_html/vendor/magento/framework/Code/Reader/ClassReader.php at line: 34
Class "ClawRock\Debug\Plugin\Collector\CacheCollectorPlugin" does not exist#0 /var/www/droner.dev/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(34): ReflectionClass->__construct()
#1 /var/www/droner.dev/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(50): Magento\Framework\Code\Reader\ClassReader->getConstructor()
#2 /var/www/droner.dev/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters()
#3 /var/www/droner.dev/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#4 /tmp/c2q_psxykuyotb.php(173): Magento\Framework\ObjectManager\ObjectManager->get()
#5 /var/www/droner.dev/public_html/vendor/magento/framework/Interception/Interceptor.php(133): Magento\Framework\Interception\PluginList\PluginList->getPlugin()
#6 /var/www/droner.dev/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Cache\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/droner.dev/public_html/generated/code/Magento/Framework/App/Cache/Interceptor.php(32): Magento\Framework\App\Cache\Interceptor->___callPlugins()
#8 /var/www/droner.dev/public_html/vendor/magento/framework/App/Cache/Proxy.php(67): Magento\Framework\App\Cache\Interceptor->load()
#9 /var/www/droner.dev/public_html/vendor/magento/framework/App/ProductMetadata.php(78): Magento\Framework\App\Cache\Proxy->load()
#10 /var/www/droner.dev/public_html/vendor/magento/framework/Console/Cli.php(101): Magento\Framework\App\ProductMetadata->getVersion()
#11 /var/www/droner.dev/public_html/bin/magento(22): Magento\Framework\Console\Cli->__construct()
#12 {main}

**Comment by makao** [comment]
You need to clear the cache.
```
rm -rf var/cache/*
```

**Comment by dronerdk** [comment]
thanks yes we know. But it does not solve it. Does it make any classes in db or other places we are not avare off?
<img width="1464" alt="Skærmbillede 2024-08-07 kl  13 33 02" src="https://github.com/user-attachments/assets/ec5f1ef8-543a-4174-9ba8-d11ccc909c14">
