### ISSUE TITLE
Missing required argument $prefix

### ISSUE THREAD

**Issue by gjportegies** [clawrock/magento2-debug#9]
Magento: 2.2.9 CE
PHP: 7.1.26

When navigating to 'Total Time' -> 'Lay-Out' I'm getting the following error: 

```Missing required argument $prefix of ClawRock\Debug\Model\ValueObject\LayoutNode.```

**Comment by makao** [comment]
I can't reproduce. Could you provide more details with reproduction?

Stack trace, Magento request which was profiled, which version of module was used etc.

**Comment by gjportegies** [comment]
@makao I guess probably somewhere in the installed theme there is invalid XML. The debug module works like a charm on other Magento 2 webshops. My bad I'll close this issue and let you know when I found the issue that caused the debugger-layout section from running.
